### Assignment 1: due week 5 just before class at 1759 hours
Given a fully connected Neural Network as follows:
1. Input (x1,x2): 2 nodes

2. First hidden layer: 10 nodes, with weights (w) and bias (b), sigmoid activation function

3. Second hidden layer: 10 nodes, with weights (w) and bias (b), sigmoid activation function

4. Output (predict): 1 node



(1) Implement this neural network in pytorch

(2) Generate the input data (x1,x2) \in [0,1] drawn from a uniform random distribution

(3) Generate the labels y = (x1*x1+x2*x2)/2

(4) Implement a loss function L = (predict-y)^2

(5) Use batch size of 1, that means feed data one point at a time into network and compute the loss. Do one time forward propagation with one data point.

(6) Compute the gradients using pytorch autograd:

a. dL/dw, dL/db

b. Print these values into a text file: torch_autograd.dat

In [4]:
import torch
torch.set_printoptions(precision=7)
#torch.__version__ 1.7.1
import numpy as np

N, D_in, H1, H2, D_out = 1, 2, 10, 10, 1

'''N is batch size, set N as 1 is what Q5 imply'''

torch.manual_seed(0)
X = torch.rand(N,2)
y = torch.empty(N,1)
y[0,0] = (X[0][0]**2 + X[0][1]**2)/2
print("Input X: ",X)
print("Input y: ",y)

class TwoLayerNet(torch.nn.Module):
    
    def __init__(self, D_in, H1,H2, D_out):
        
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H1)
        self.linear2 = torch.nn.Linear(H1, H2)
        self.linear3 = torch.nn.Linear(H2, D_out)

    def forward(self, x):
        sigmoid = torch.nn.Sigmoid()        
        h1_sigmoid = sigmoid(self.linear1(x))       
        h2_sigmoid = sigmoid(self.linear2(h1_sigmoid))  
        y_pred = self.linear3(h2_sigmoid)
        return y_pred

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H1,H2, D_out)

#Save the initial parameters for my own defined BP process
b3 = model.linear3.bias
w3 = model.linear3.weight.t()
b2 = model.linear2.bias
w2 = model.linear2.weight.t()
b1 = model.linear1.bias
w1 = model.linear1.weight.t()

loss_fn = torch.nn.MSELoss(reduction='sum')
#def loss_fn(y, y_pred):
#    return torch.sum((y_pred - y) ** 2) #pretty the same with MSELoss

learning_rate = 0.1

for t in range(1):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(X)
    
    # Compute and print loss
    loss = loss_fn(y_pred, y)
    print('step %d: loss=%f   ' % (t+1, loss.item()))   
    model.zero_grad()
    loss.backward()
    
    #As we only need the 1st time gradient, no need to update the parameters
    '''
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad
    '''  
    
    # in Linear class __init__，the shape of weight[out_features, in_features], need to be transformed
    print("First hidden layer weights gradient: \n",model.linear1.weight.grad.t())
    print("First hidden layer bias gradient: \n", model.linear1.bias.grad)
    print("Second hidden layer weight gradient:\n", model.linear2.weight.grad.t())
    print("Second hidden layer bias gradient: \n",model.linear2.bias.grad)
    print("Output layer bias gradient: \n",model.linear3.bias.grad)
    print("Output layer weight gradient: \n",model.linear3.weight.grad.t())
    
print("Predicted y:",y_pred)

Input X:  tensor([[0.4962566, 0.7682218]])
Input y:  tensor([[0.4182177]])
step 1: loss=0.986679   
First hidden layer weights gradient: 
 tensor([[-0.0027822,  0.0071077, -0.0034240, -0.0119751, -0.0009449, -0.0062731,
         -0.0078180, -0.0039982,  0.0051486,  0.0050384],
        [-0.0043070,  0.0110030, -0.0053005, -0.0185379, -0.0014627, -0.0097110,
         -0.0121026, -0.0061894,  0.0079701,  0.0077997]])
First hidden layer bias gradient: 
 tensor([-0.0056064,  0.0143226, -0.0068997, -0.0241309, -0.0019041, -0.0126409,
        -0.0157540, -0.0080567,  0.0103748,  0.0101529])
Second hidden layer weight gradient:
 tensor([[-0.0402310,  0.0034391,  0.0419600,  0.0224192, -0.0302611,  0.0003073,
          0.0235890,  0.0362652,  0.0421244,  0.0394331],
        [-0.0839402,  0.0071756,  0.0875477,  0.0467767, -0.0631384,  0.0006411,
          0.0492174,  0.0756657,  0.0878907,  0.0822755],
        [-0.0766456,  0.0065520,  0.0799396,  0.0427117, -0.0576515,  0.0005854,
          0.


(7) Implement the forward propagation and backpropagation algorithm from scratch,without using pytorch autograd, compute the gradients using your implementation

a. dL/dw, dL/db

b. Print these values into a text file: my_autograd.dat

(8) Compare the two files torch_autograd.dat and my_autograd.dat and show that they give the same values up to numerical precision errors

In [176]:
def sigmoid_derivationx(y):
    return y * (1 - y)

learning_rate = 0.1
for t in range(1):
    # Forward pass: compute predicted y 
    h1 = X.mm(w1) +b1 # N*D_in x D_in* H1 + N*H1 = N*H1
    h1_sigmoid = torch.sigmoid(h1)   #N*H1
    h2 = h1_sigmoid.mm(w2) +b2   #N*H1 x H1*H2 + N*H2  = N *H2
    h2_sigmoid = torch.sigmoid(h2)#N * H2   
    y_pred  = h2_sigmoid.mm(w3) +b3 #N*H2 x H2*D_out + N*D_out= N * D_out
         
    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    print('step %d: loss=%f   ' % (t+1, loss))
    
    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = -2.0 *(y - y_pred)#N    
    delta = grad_y_pred#N*D_out                           
    grad_w3 = h2_sigmoid.T.mm(delta)#H2*N mm N*D_out =    H2* D_out                    
    grad_b3 = delta  #N*D_out 
    
    delta = delta.mm(w3.T)*sigmoid_derivationx(h2_sigmoid)#N*D_out x D_out*H2 = N*10 . N *10 =N *10
    grad_w2 = h1_sigmoid.T.mm(delta)#10*N  x N*10 = 10*10
    grad_b2 = delta   # 1*N x N*10  = 1*10
    
    delta = delta.mm(w2.T)*sigmoid_derivationx(h1_sigmoid)#N*10 X 10*10 = N *10 * N *10 = N *10
    grad_w1 = X.T.mm(delta)# 2*N X N*10 = 2*10
    grad_b1 =  delta  # 1*N x N * 10 
     
    print("First hidden layer weights gradient: \n",grad_w1)
    print("First hidden layer bias gradient: \n", grad_b1)
    print("Second hidden layer weight gradient:\n", grad_w2)
    print("Second hidden layer bias gradient: \n",grad_b2)
    print("Output layer bias gradient: \n",grad_b3)   
    print("Output layer weight gradient: \n",grad_w3)  
    
    #update weights
    w3 = w3 - learning_rate * grad_w3  
    w2 = w2 - learning_rate * grad_w2
    w1 = w1 - learning_rate * grad_w1
    
    b3 = b3 - learning_rate * grad_b3
    b2 = b2 - learning_rate * grad_b2
    b1 = b1 - learning_rate * grad_b1  
print(y_pred)

step 1: loss=0.986679   
First hidden layer weights gradient: 
 tensor([[-0.0027822,  0.0071077, -0.0034240, -0.0119751, -0.0009449, -0.0062731,
         -0.0078180, -0.0039982,  0.0051486,  0.0050384],
        [-0.0043070,  0.0110030, -0.0053005, -0.0185379, -0.0014627, -0.0097110,
         -0.0121026, -0.0061894,  0.0079701,  0.0077997]],
       grad_fn=<MmBackward>)
First hidden layer bias gradient: 
 tensor([[-0.0056064,  0.0143226, -0.0068997, -0.0241309, -0.0019041, -0.0126409,
         -0.0157540, -0.0080567,  0.0103748,  0.0101529]],
       grad_fn=<MulBackward0>)
Second hidden layer weight gradient:
 tensor([[-0.0402310,  0.0034391,  0.0419600,  0.0224192, -0.0302611,  0.0003073,
          0.0235890,  0.0362652,  0.0421244,  0.0394331],
        [-0.0839402,  0.0071756,  0.0875477,  0.0467767, -0.0631384,  0.0006411,
          0.0492174,  0.0756657,  0.0878907,  0.0822755],
        [-0.0766456,  0.0065520,  0.0799396,  0.0427117, -0.0576515,  0.0005854,
          0.0449403,  0.

In [5]:
N, D_in, H1, H2, D_out = 1, 2, 10, 10, 1 #Only N: number of input can be tuned
np.random.seed(10)

X = X.numpy()
y = y.numpy()
w1 = w1.detach().numpy()
w2 = w2.detach().numpy()
w3 = w3.detach().numpy()

b1 = b1.detach().numpy()
b2 = b2.detach().numpy()
b3 = b3.detach().numpy()


learning_rate = 0.1
def sigmoid(x):
        return 1.0/(1+np.exp(-x))
    
def sigmoid_derivationx(y):
    return y * (1 - y)

for t in range(1):
    # forward
    h1 = X.dot(w1) +b1 # N*2 x 2* 10 + 1*10 = N*10
    h1_sigmoid = sigmoid(h1)#N*10
    
    h2 = h1_sigmoid.dot(w2) +b2 #N*10 x 10*10 + 1*10  = N *10
    h2_sigmoid = sigmoid(h2)#N * 10
    
    h3 = h2_sigmoid.dot(w3) +b3 #N*10 x 10*1 = N * 1
    y_pred = h3
    #print(y_pred)
    #compute loss L = (predict-y)^2
    loss = np.square(y_pred -y).sum() #N 
    print('step %d: loss=%f   ' % (t, loss))    
    #backward pass
    #compute gradient
    grad_y_pred = 2.0 *(y_pred - y)#N    
    
    delta = grad_y_pred#N*1
    grad_w3 = np.dot(h2_sigmoid.T, delta)#10*N, N*1 = 10*1
    grad_b3 = np.ones(N).dot(delta)   # 1*N(h3 shape.T) x N*1 =1
    
    
    delta = np.dot(delta, w3.T)*sigmoid_derivationx(h2_sigmoid)#N*1 x 1*10 = N*10 . N *10 =N *10
    grad_w2 = np.dot(h1_sigmoid.T , delta)#10*N  x N*10 = 10*10
    grad_b2 = np.ones(N).dot(delta)   # 1*N x N*10  = 1*10
    
    delta = np.dot(delta, w2.T)*sigmoid_derivationx(h1_sigmoid)#N*10 X 10*10 = N *10 * N *10 = N *10
    grad_w1 = np.dot(X.T , delta)# 2*N X N*10 = 2*10
    grad_b1 =  np.ones(N).dot(delta)  # 1*N x N * 10 
    print(grad_w3)
    #update weights
    w3 -= learning_rate * grad_w3
    w2 -= learning_rate * grad_w2
    w1 -= learning_rate * grad_w1
    
    b3 -= learning_rate * grad_b3
    b2 -= learning_rate * grad_b2
    b1 -= learning_rate * grad_b1
    
print(y, y_pred)

step 0: loss=0.986679   
[[-0.665516  ]
 [-0.9933792 ]
 [-1.1256515 ]
 [-1.0672039 ]
 [-1.2473825 ]
 [-0.93714494]
 [-1.0377069 ]
 [-0.9243824 ]
 [-1.2229568 ]
 [-0.86192024]]
[[0.41821766]] [[-0.5750997]]
